version: 2.1
executors:
  mypublisher:
#    working_directory: ~/repo
    docker:
      - image: circleci/node:10
jobs:
  # Install
  # Test
  # Build && Publish
  install:
    executor: mypublisher
    steps:
      - checkout
      - run:
          name: Install node
          command: npm install
  build_image:
    executor: mypublisher
    steps:
      - setup_remote_docker
      - run:
          name: Build image docker
          command: docker build -f docker/api/Dockerfile -t larnico/nodejs-api_team11:latest .
      - run:
          name: Publication sur Docker Hub
          command: |
              echo "$DOCKERHUB_pwd" | docker login -u larnico --password-stdin
              docker push larnico/nodejs-api_team11:latest
  update_changelog:
    docker:
      - image: circleci/circleci-cli
    steps:
      - setup_remote_docker
      - run:
          name: test changelog
          command: |
              echo 'github'
workflows:
  version: 2
  dev:
    jobs:
      - install
      - build_image:
          requires:
            - install
          filters:
            branches:
              only: dev
  prod:
    jobs:
      - install
      - build_image:
          requires:
            - install
      - update_changelog:
          requires:
            - build_image
          filters:
            branches:
              only: master
              ignore: dev
            tags:
              only: /[0-9]{1,}.[0-9]{1,}.[0-9]{1,}