version: 2.1
executors:
  mypublisher:
#    working_directory: ~/repo
    docker:
      - image: circleci/node:10
jobs:
  # Install
  # Test
  # Build && Publish
  install:
    executor: mypublisher
    steps:
      - checkout
      - run:
          name: Install node
          command: npm install
  build_image:
    executor: mypublisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image docker
          command: docker build -f docker/api/Dockerfile -t larnico/nodejs-api_team11:latest .
      - run:
          name: Publication sur Docker Hub
          command: |
              echo "$DOCKERHUB_pwd" | docker login -u larnico --password-stdin
              docker push larnico/nodejs-api_team11:latest
  github_release:
    steps:
      - run:
          name: Publish Release on GitHub
          command: |
            go get https://github.com/YI-B3-Devops/tp2-team-11
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} .
workflows:
  version: 2
  build-master:
    jobs:
      - install
      - build_image:
          requires:
            - install
      - github_realase:
          requires:
            - build_image
          filters:
            branches:
              only: master
