version: 2.1
executors:
  my-publisher:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
jobs:
  build:
    executor: my-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t larnico\nodejs-api_team11:latest docker/api/
